# 1. Create a 3x3x3 array with random values 

In [7]:
import numpy as np
arr = np.empty((3,3,3))
print(arr)

[[[0.20085942 0.70100546 0.27437233]
  [0.80909406 0.41126504 0.70096485]
  [0.5969674  0.82247256 0.48668304]]

 [[0.80031589 0.85497564 0.57388696]
  [0.8929318  0.4746925  0.41610675]
  [0.07539503 0.14535089 0.77725672]]

 [[0.39458978 0.87185578 0.69067123]
  [0.36695668 0.84635141 0.82287251]
  [0.50899808 0.27067913 0.01812914]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [23]:
arr2 = np.diag(1+np.arange(4),-1)
print (arr2)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [30]:
arr3 = np.zeros((8,8),dtype = int)
arr3[1::2,::2] = 1
arr3[::2,1::2] = 1
print(arr3)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [55]:
arr5 = np.random.random((5,5))
arr5max,arr5min = arr5.max(), arr5.min()
arr5= (arr5-arr5min)/(arr5max-arr5min)
print (arr5)

[[1.         0.68284945 0.65201052 0.84041042 0.7154251 ]
 [0.55831233 0.24588826 0.05375647 0.5151234  0.2050456 ]
 [0.74768159 0.55759844 0.32969902 0.78639172 0.39574548]
 [0.44836762 0.77574317 0.         0.00847592 0.391768  ]
 [0.29672469 0.73547692 0.51716954 0.28571075 0.41612101]]


# 5.  How to find common values between two arrays?

In [15]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2 = np.array([[1,23,93],[4,161,6],[7,57,9]])
arr1 = arr1.flatten()
arr2 = arr2.flatten()
for ar in arr1:
    if ar in arr2:
        print(ar)


1
4
6
7
9


# 6.How to get the dates of yesterday, today and tomorrow?

In [15]:
import numpy as np
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2020-07-27
Today:  2020-07-28
Tomorrow:  2020-07-29


# 7. Consider two random array A and B, check if they are equal

In [13]:
A = np.empty((3,3))
B = np.empty((3,3))
flag = 1
print(A)
print(B)
if A.shape != B.shape:
    print('Not equal')
else:
    A = A.flatten()
    B = B.flatten()
    for i in A:
        if i not in B:
            flag = 0
            break
if flag == 0:
    print("Not Equal")
else:
    print('Equal')


[[0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 6.95644429e-321]
 [8.34438346e-308 7.23149004e-308 0.00000000e+000]]
[[0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 6.73905541e-321]
 [1.15706964e-306 2.33419537e-312 2.46151512e-312]]
Not Equal


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [14]:
import numpy as np
val = np.random.randn(10)
maximum = val.max()
val.sort()
print(val)
print()
print("maximum value is",maximum)
print()
val[9] = 0
print("replacing max value with zero")
print()
print(val)

[-1.43495243 -1.19718463 -0.3816129  -0.35215634  1.04306382  1.1101154
  1.18042321  1.40230785  1.40262243  2.48911278]

maximum value is 2.4891127805887647

replacing max value with zero

[-1.43495243 -1.19718463 -0.3816129  -0.35215634  1.04306382  1.1101154
  1.18042321  1.40230785  1.40262243  0.        ]


# 9. How to print all the values of an array?

In [38]:
arr4 = np.array([[1,6,9],[3,5,6],[0,9,7]])
for i in range(3):
    for j in range(3):
        print(arr4[i,j],end=' ')
    print()


1 6 9 
3 5 6 
0 9 7 


# 10.Subtract the mean of each row of a matrix

In [71]:
from functools import reduce
arr6 = np.array([[5,6,7],[3,4,5],[0,1,2]])
sub = []
for i in range(3):
    sum = 0
    for j in range(3):
        sum += arr6[i,j]
    avg=sum/3
    sub.append(avg)
    print(avg)
k = reduce(lambda x,y : x -y,sub)
print("subtraction of mean of each row",k)




6.0
4.0
1.0
subtraction of mean of each row 1.0


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [21]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),10)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[3. 1. 3. 1. 1. 4. 2. 1. 3. 1.]


# 12.How to get the diagonal of a dot product?

In [77]:
a = np.array([[5,6,2],[1,10,6],[8,6,9]])
b = np.array([[15,7,9],[10,12,3],[1,2,3]])
f = np.dot(a,b)
print("dot product of two arrays")
print(f)
print("diagonal values of dot product",np.diag(f,k = 0))

dot product of two arrays
[[137 111  69]
 [121 139  57]
 [189 146 117]]
diagonal values of dot product [137 139 117]


# 13.How to find the most frequent value in an array?

In [19]:
random = np.random.randint(0,10,30)
print("original array")
print()
print(random)
print()
print("most frequent number")
print(np.bincount(random).argmax())

original array

[2 9 6 5 1 8 5 0 8 9 5 6 3 9 9 5 9 3 8 6 8 3 5 6 9 0 0 0 1 8]

most frequent number
9


# 14.How to get the n largest values of an array

In [22]:
import numpy as np
x = np.arange(10)
print("Original array:")
print(x)
np.random.shuffle(x)
n = 1
print (x[np.argsort(x)[-n:]])

Original array:
[0 1 2 3 4 5 6 7 8 9]
[9]


# 15.How to create a record array from a regular array?

In [24]:
import numpy as np
arra1 = np.array([("Manish", 88.5, 90),
                 ("sirisha", 87, 99),
             ("sandeep", 85.5, 91)])
print("Original arrays:")
print(arra1)
print("\nRecord array;")
result = np.core.records.fromarrays(arra1.T,
                              names='col1, col2, col3',
                              formats = 'S80, f8, i8')
print(result)


Original arrays:
[['Manish' '88.5' '90']
 ['sirisha' '87' '99']
 ['sandeep' '85.5' '91']]

Record array;
[(b'Manish', 88.5, 90) (b'sirisha', 87. , 99) (b'sandeep', 85.5, 91)]
